# Generated by Django 5.2.14 on 2026-05-29 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_question',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='waxing_waiver',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='client_waiver',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
